### ISSUE TITLE
Pose-only optimizations

### ISSUE THREAD

**Issue by sapir1779** [fixstars/cuda-bundle-adjustment#7]
Whenever I try to only optimize the Poses (PoseVertex) by fixing all of the landmarks and not fixing the poses, I get the following Eigen error:
```
/usr/include/eigen3/Eigen/src/Core/PlainObjectBase.h:312: void Eigen::PlainObjectBase<Derived>::resize(Eigen::Index) [with Derived = Eigen::Matrix<int, -1, 1>; Eigen::Index = long int]: Assertion `((SizeAtCompileTime == Dynamic && (MaxSizeAtCompileTime==Dynamic || size<=MaxSizeAtCompileTime)) || SizeAtCompileTime == size) && size>=0' failed
```

I've tested that with the provided  `ba_kitti_07.json` sample and get the error when I fix the landmarks and not the poses.

Is the library not suited for such cases?

Thanks in advance,
S.

**Comment by atakagi-fixstars** [comment]
Hi, @cvmufc1 
Thank you for notifying.

I could reproduce the same error.
I found this library can't handle pose-only optimization, special treatment is required in such case.
I want to support in the future.

Regards,

**Comment by atakagi-fixstars** [comment]
We added support pose-only optimizations in the [latest release](https://github.com/fixstars/cuda-bundle-adjustment/releases/tag/2.0.0).

Regards,
